import Head from 'next/head'
import Layout from '../components/Layout'
import Image from 'next/image'
import profilePic from '../../public/images/profile/Profile1.png'
import AnimatedText from '../components/AnimatedText'
import WordSwapper from '../components/WordSwapper'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className="flex w-full justify-between items-center">
            <div className="w-1/2">
              <Image src={profilePic} alt="ProfileImage" className="w-full h-auto"></Image>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText text="THIS IS MOHAMMADREZA, A" className='!text-6xl !text-left' swap={true}>
              </AnimatedText>
              <p>I am a PhD candidate in Materials Science and Engineering at Illinois
                Institute of Technology, working on 3D printing of metals.</p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
