import Head from "next/head";
import Layout from "../components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/Profile1.png";
import AnimatedText from "../components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "../components/icons";
import { CustomLink } from "../components/NavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex w-full justify-between items-center">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="ProfileImage"
                className="w-full h-auto"
              ></Image>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="THIS IS MOHAMMADREZA, A"
                className="!text-6xl !text-left"
                swap={true}
              ></AnimatedText>
              <p className="my-4 font-medium text-lg">
                I am a PhD candidate in Materials Science and Engineering at
                Illinois Institute of Technology, working on 3D printing of
                metals.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/CV - Mohammadreza Asherloo.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6
                  rounded-lg text-lg font-semibold hover:bg-light
                  hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  download={true}
                >
                  Curriculum Vitae <LinkArrow className={"w-auto ml-1"} />
                </Link>
                <Link
                  href="mailto:masherloo@hawk.iit.edu"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dard hover:underline underline-offset-4 hover:font-semibold"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
